#https://dev.to/darlanalves/automated-semantic-releases-with-npm-and-github-actions-1bmj

name: release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build, if needed
        run: npm run build --if-present
      - name: Run tests
        run: npm test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
